### ISSUE TITLE
Missing module docstring

### ISSUE THREAD

**Issue by ejyager00** [s-gannon/hope-and-pray-sort#3]
Although the file `hopeAndPraySort.py` now has a function docstring for `hopeAndPraySort()`, it still does not contain a module docstring.

**Comment by s-gannon** [comment]
I don't know what that is

**Comment by s-gannon** [comment]
Please include a link to some reference so I can add it

**Comment by ejyager00** [comment]
https://realpython.com/documenting-python-code/#package-and-module-docstrings

**Comment by s-gannon** [comment]
Done.
